my_app/user/models.py
from my_app import db

class User(db.Model):
    #__tablename__ = 'user_db'
    username = db.Column(db.String(15),primary_key=True)
    password = db.Column(db.String(12))
    dni = db.Column(db.String(9))
    nombre = db.Column(db.String(20))
    apellidos = db.Column(db.String(40))
    edad = db.Column(db.Integer)

    def __repr__(self):
        return '<User %r>' % self.username

my_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SECRET_KEY'] = '123456790'
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:root@localhost:3306/usuarios_db'
#app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql+psycopg2://postgres:postgres@localhost/catalog_db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True

db = SQLAlchemy(app)

from my_app.user.views import user_blueprint
app.register_blueprint(user_blueprint)

db.create_all()

my_app/user/views.py
from werkzeug import abort
from flask import render_template
from flask import Blueprint
from my_app.user.models import User

user_blueprint = Blueprint('user', __name__)


@user_blueprint.context_processor
def some_processor():
    def full_name(user):
        return '{0} / {1} / dni [{2}] / edad: {3}'.format(user.nombre, user.apellidos, user.dni, user.edad)
    return {'full_name': full_name}


@user_blueprint.route('/')
@user_blueprint.route('/home')
def home():
    return render_template('home.html', users=User.query.all())

@user_blueprint.route('/user/<key>')
def user(key):
    user = User.query.filter(User.username == key).first()
    if not user:
        abort(404)
    return render_template('user.html', user=user)

my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Framework Cookbook</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{{ url_for('user.home') }}">Flask Promenade</a>
        </div>
      </div>
    </div>
    <div class="container">
    {% block container %}{% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  </body>
</html>

my_app/templates/home.html
{% extends 'base.html' %}

{% block container %}
  <div class="top-pad">
    {% for user in users %}
      <div class="well">
        <h2>
          <a href="{{ url_for('user.user', key=user.username) }}">{{ user.username }}</a>
          <small>{{ user.nombre}} // {{ user.apellidos}}</small>
        </h2>
      </div>
    {% endfor %}
  </div>
{% endblock %}

my_app/templates/user.html
{% extends 'home.html' %}

{% block container %}
  <div class="top-pad">
    <h4>{{ full_name(user) }}</h4>
    <h1>{{ user.username }}
      <small>{{ user.nombre }}</small>
    </h1>
    <h3>{{ user.apellidos | title }}</h3>
  </div>
{% endblock %}